# all units are in cgs.
# this is designed as a test for 
# gravity and pressure rules, using an approximation
# of the isothermal sphere for an ideal gas

################# Simulation Parameters ###############
name = "disk" # name to save to
# seed = 127
save_skip = 25  # number of frames to skip when saving

N = 300         # number of simulation particles
t_end = 1e9     # years to integrate for

adaptive = true


R_virial = 1e3
c = 10          # density compactness parameters


phys_gravity = true
phys_DM = false

phys_pressure = true
phys_conduction = true

phys_feedback = false
phys_star_formation = false



