# all units are in cgs.
# this is designed as a test for 
# gravity and pressure rules, using an approximation
# of the isothermal sphere for an ideal gas

################# Simulation Parameters ###############
name = "static_eq" # name to save to
# seed = 127
save_skip = 25  # number of frames to skip when saving

N = 500         # number of simulation particles
t_end = 1e7     # years to integrate for

dt_min = 1e3    # minimum timestep
dt_max = 1e5
dt_rel_max = 10
adaptive = true


theta = 0.05    # BH theta parameter
eta = 3         # density estimation parameter

# density estimation parameters
tol = 1e-4
rho_maxiter = 100
rho_max = 1e15 # min and maximum densities allowed
rho_min = 1e-40

h_min = 0.1
h_max = 1000


r_plummer = 0.1 # Gravitational softening radius, in terms of h



################# Initial Conditions #####################
# these are in Msun
M_tot = 1e8

# in parsecs
R_virial = 1e3
c = 10          # density compactness parameters



################# Evolutionary Parameters ################
K_cond = 2e7    # conduction constant
n_K = 0.05
sfe = 0.00      # star formation effeciency

Jfuv = 0        # far UV energy density
Gamma_0 = 0     # stellar feedback factor
f_rad = 0       # radiative heating fraction


alpha_visc = 1
beta_visc = 2
eta_visc = 0.1

################# Physics #########################

phys_gravity = true
phys_DM = false

phys_pressure = true
phys_conduction = false
phys_visc = false

phys_feedback = false
phys_star_formation = false


