################# Simulation Parameters ###############

name = "two_body_p" # name to save to
# seed = 127

save_skip = 100  # number of frames to skip when saving
N = 2         # number of simulation particles
NN = 2
t_end = 1e9     # years to integrate for

adaptive = true

################# Physics #########################

phys_gravity = false
phys_DM = false

phys_pressure = true
phys_conduction = false

phys_star_formation = false


phys_visc = false
