# all units are in cgs.
# this is designed as a test for initial

################# Simulation Parameters ###############
name = "two_body"

N = 2         # number of simulation particles
NN = 2
t_end = 1e10     # years to integrate for
save_skip = 10

eta = 1         # density estimation parameter

dt_min = 1e4    
dt_max = 1024e4   

adaptive=true

dt_rel_max = 16    # minimum timestep
tol = 1e-3
h_maxiter = 20
h_max = 1
h_min = 0.1



################# Physics #########################

phys_gravity = true
phys_DM = false

phys_pressure = false
phys_conduction = false
phys_visc = false

phys_feedback = false
phys_star_formation = false


